language: python
python:
  - '3.4'
  - '3.5'
  - '3.6'
  - '3.7'
  - '3.8'
before_install:
  - pip install -r requirements.txt
script:
  - nosetests -v --with-coverage --cover-xml
after_success:
  - bash <(curl -s https://codecov.io/bash)
